apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: backup
provisioner: ebs.csi.aws.com  # Use AWS EBS CSI driver
parameters:
  type: gp2
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: backup
