apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      serviceAccountName: mongo-backup  # Ensure the pod uses the service account with S3 access
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: passVerify
        - name: MONGO_INITDB_DATABASE
          value: inventory
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
        - mountPath: /usr/local/bin/aws
          name: aws-cli-bin
        - mountPath: /etc/cron.d
          name: backup-cron
      volumes:
      - name: aws-cli-bin
        emptyDir: {}
      - name: backup-cron
        configMap:
          name: backup-cron
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      storageClassName: backup  # AWS EBS
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort