apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: henriksin1/inventory-test_inventory-service:latest # Replace with your image name or build it before
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://root:passVerify@mongo:27017/inventory?authSource=admin"
        - name: RABBITMQ_URI
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: ELASTICSEARCH_HOST
          value: "http://elastic:elasticpassword@elasticsearch:9200"
        - name: PORT
          value: "3000"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /health  # Adjust to your actual health check endpoint
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
