apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongotest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongotest
  template:
    metadata:
      labels:
        app: mongotest
    spec:
      containers:
      - name: test
        image: mongo:6.0
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongotest
spec:
  selector:
    app: mongotest
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
