name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  debug-oidc-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Request OIDC Token
        id: oidc-token
        run: |
          echo "TOKEN=$(curl -H 'Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN' \
          \"$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com\" | jq -r '.value')" >> $GITHUB_ENV

      - name: Save Token to File
        run: echo "$TOKEN" > github-oidc-token.txt

      - name: Upload Token Artifact
        uses: actions/upload-artifact@v4
        with:
          name: oidc-token
          path: github-oidc-token.txt
          retention-days: 1
