name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  debug-oidc-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Request OIDC Token
        id: oidc-token
        run: |
          echo "TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')" >> $GITHUB_ENV

      - name: Save Token to File
        run: echo "$TOKEN" > github-oidc-token.txt

      - name: Display Token (for debugging)
        run: cat github-oidc-token.txt
